#
# Find TBB
#

set(TBB_VERSION_REQUIRED "2.0")

if(NOT TBB_ROOT)
	set(TBB_ROOT $ENV{TBB_ROOT})
endif()
if(NOT TBB_ROOT)
	set(TBB_ROOT $ENV{TBBROOT})
endif()

# Detect changed TBB_ROOT
if(NOT TBB_ROOT STREQUAL TBB_ROOT_LAST)
	unset(TBB_INCLUDE_DIR			CACHE)
	unset(TBB_LIBRARY				CACHE)
	unset(TBB_LIBRARY_DEBUG			CACHE)
	unset(TBB_LIBRARY_MALLOC		CACHE)
	unset(TBB_LIBRARY_MALLOC_DEBUG	CACHE)
	unset(TBB_INCLUDE_DIR_MIC		CACHE)
	unset(TBB_LIBRARY_MIC			CACHE)
	unset(TBB_LIBRARY_MALLOC_MIC	CACHE)
endif()