// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "Animation.h"
#include "Frame.h"

using namespace System;
using namespace System::Runtime::InteropServices;

CubbyFlowSharp::CubbyFlow::Animation::Animation(::CubbyFlow::Animation* native)
    : __ownsNativeInstance(false)
{
    NativePtr = native;
}

CubbyFlowSharp::CubbyFlow::Animation^ CubbyFlowSharp::CubbyFlow::Animation::__CreateInstance(::System::IntPtr native)
{
    return gcnew ::CubbyFlowSharp::CubbyFlow::Animation((::CubbyFlow::Animation*) native.ToPointer());
}

CubbyFlowSharp::CubbyFlow::Animation::~Animation()
{
    delete NativePtr;
}

CubbyFlowSharp::CubbyFlow::Animation::Animation()
{
    __ownsNativeInstance = true;
}

void CubbyFlowSharp::CubbyFlow::Animation::Update(CubbyFlowSharp::CubbyFlow::Frame^ frame)
{
    if (ReferenceEquals(frame, nullptr))
        throw gcnew ::System::ArgumentNullException("frame", "Cannot be null because it is a C++ reference (&).");
    auto &__arg0 = *(::CubbyFlow::Frame*)frame->NativePtr;
    ((::CubbyFlow::Animation*)NativePtr)->Update(__arg0);
}

CubbyFlowSharp::CubbyFlow::Animation::Animation(CubbyFlowSharp::CubbyFlow::Animation^ _0)
{
    __ownsNativeInstance = true;
}

System::IntPtr CubbyFlowSharp::CubbyFlow::Animation::__Instance::get()
{
    return System::IntPtr(NativePtr);
}

void CubbyFlowSharp::CubbyFlow::Animation::__Instance::set(System::IntPtr object)
{
    NativePtr = (::CubbyFlow::Animation*)object.ToPointer();
}
