// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "ArrayAccessor.h"
#include "Point2.h"
#include "Point3.h"
#include "Size2.h"
#include "Size3.h"

using namespace System;
using namespace System::Runtime::InteropServices;

