// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "Frame.h"

using namespace System;
using namespace System::Runtime::InteropServices;

CubbyFlowSharp::CubbyFlow::Frame::Frame(::CubbyFlow::Frame* native)
    : __ownsNativeInstance(false)
{
    NativePtr = native;
}

CubbyFlowSharp::CubbyFlow::Frame^ CubbyFlowSharp::CubbyFlow::Frame::__CreateInstance(::System::IntPtr native)
{
    return gcnew ::CubbyFlowSharp::CubbyFlow::Frame((::CubbyFlow::Frame*) native.ToPointer());
}

CubbyFlowSharp::CubbyFlow::Frame::~Frame()
{
    delete NativePtr;
}

CubbyFlowSharp::CubbyFlow::Frame::Frame()
{
    __ownsNativeInstance = true;
    NativePtr = new ::CubbyFlow::Frame();
}

CubbyFlowSharp::CubbyFlow::Frame::Frame(int newIndex, double newTimeIntervalInSeconds)
{
    __ownsNativeInstance = true;
    NativePtr = new ::CubbyFlow::Frame(newIndex, newTimeIntervalInSeconds);
}

void CubbyFlowSharp::CubbyFlow::Frame::Advance()
{
    ((::CubbyFlow::Frame*)NativePtr)->Advance();
}

void CubbyFlowSharp::CubbyFlow::Frame::Advance(int delta)
{
    ((::CubbyFlow::Frame*)NativePtr)->Advance(delta);
}

CubbyFlowSharp::CubbyFlow::Frame^ CubbyFlowSharp::CubbyFlow::Frame::operator++(CubbyFlowSharp::CubbyFlow::Frame^ __op)
{
    if (ReferenceEquals(__op, nullptr))
        throw gcnew ::System::ArgumentNullException("__op", "Cannot be null because it is a C++ reference (&).");
    auto &__arg0 = *(::CubbyFlow::Frame*)__op->NativePtr;
    auto &__ret = ++ __arg0;
    return (CubbyFlowSharp::CubbyFlow::Frame^)((&__ret == nullptr) ? nullptr : gcnew CubbyFlowSharp::CubbyFlow::Frame((::CubbyFlow::Frame*)&__ret));
}

CubbyFlowSharp::CubbyFlow::Frame::Frame(CubbyFlowSharp::CubbyFlow::Frame^ _0)
{
    __ownsNativeInstance = true;
    if (ReferenceEquals(_0, nullptr))
        throw gcnew ::System::ArgumentNullException("_0", "Cannot be null because it is a C++ reference (&).");
    auto &__arg0 = *(::CubbyFlow::Frame*)_0->NativePtr;
    NativePtr = new ::CubbyFlow::Frame(__arg0);
}

System::IntPtr CubbyFlowSharp::CubbyFlow::Frame::__Instance::get()
{
    return System::IntPtr(NativePtr);
}

void CubbyFlowSharp::CubbyFlow::Frame::__Instance::set(System::IntPtr object)
{
    NativePtr = (::CubbyFlow::Frame*)object.ToPointer();
}

int CubbyFlowSharp::CubbyFlow::Frame::Index::get()
{
    return ((::CubbyFlow::Frame*)NativePtr)->index;
}

void CubbyFlowSharp::CubbyFlow::Frame::Index::set(int value)
{
    ((::CubbyFlow::Frame*)NativePtr)->index = value;
}

double CubbyFlowSharp::CubbyFlow::Frame::TimeIntervalInSeconds::get()
{
    return ((::CubbyFlow::Frame*)NativePtr)->timeIntervalInSeconds;
}

void CubbyFlowSharp::CubbyFlow::Frame::TimeIntervalInSeconds::set(double value)
{
    ((::CubbyFlow::Frame*)NativePtr)->timeIntervalInSeconds = value;
}

double CubbyFlowSharp::CubbyFlow::Frame::TimeInSeconds::get()
{
    auto __ret = ((::CubbyFlow::Frame*)NativePtr)->TimeInSeconds();
    return __ret;
}

