// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "CppSharp.h"
#include <C:/Users/utilForever/Documents/GitHub/CubbyFlow/Includes/Core/Math/MathUtils-Impl.h>

namespace CubbyFlowSharp
{
}

namespace CubbyFlowSharp
{
    namespace CubbyFlow
    {
    }
}
