// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "CppSharp.h"
#include <C:/Users/utilForever/Documents/GitHub/CubbyFlow/Includes/Core/Utils/Parallel.h>

namespace CubbyFlowSharp
{
    namespace CubbyFlow
    {
        enum struct ExecutionPolicy;
    }
}

namespace CubbyFlowSharp
{
    namespace CubbyFlow
    {
        /// <summary>Execution policy tag.</summary>
        public enum struct ExecutionPolicy
        {
            Serial = 0,
            Parallel = 1
        };

        public ref class Parallel
        {
        public:
            /// <summary>Sets maximum number of threads to use.</summary>
            static void SetMaxNumberOfThreads(unsigned int numThreads);
            /// <summary>Returns maximum number of threads to use.</summary>
            static unsigned int GetMaxNumberOfThreads();
        };
    }
}
