// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#include "Parallel.h"

using namespace System;
using namespace System::Runtime::InteropServices;

/// <summary>Sets maximum number of threads to use.</summary>
void CubbyFlowSharp::CubbyFlow::Parallel::SetMaxNumberOfThreads(unsigned int numThreads)
{
    ::CubbyFlow::SetMaxNumberOfThreads(numThreads);
}

/// <summary>Returns maximum number of threads to use.</summary>
unsigned int CubbyFlowSharp::CubbyFlow::Parallel::GetMaxNumberOfThreads()
{
    auto __ret = ::CubbyFlow::GetMaxNumberOfThreads();
    return __ret;
}

