// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "CppSharp.h"
#include <C:/Users/utilForever/Documents/GitHub/CubbyFlow/Includes/Core/Point/Point2.h>

namespace CubbyFlowSharp
{
    namespace CubbyFlow
    {
        ref class Point;
    }
}

namespace CubbyFlowSharp
{
    namespace CubbyFlow
    {
    }
}
